### ISSUE TITLE
[01] Use DINOv2 for VisualDNA backbone

### ISSUE THREAD

**Issue by kbpranav** [DLL-Project-Incremental-Learning/VisualDNA#1]
DINOv2 is supported if you install from the feature/add-dinov2 branch ((https://github.com/bramtoula/vdna/tree/feature/add-dinov2)).

**Comment by SantoshParit** [comment]
Done, integrated those changes and the code is added.

**Comment by SantoshParit** [comment]
made change in this commit: https://github.com/DLL-Project-Incremental-Learning/VisualDNA/commit/28827b8c3b6e8aebfefe7114e9c7163adfc4c46e

@kbpranav @hl49
